name: Auto Fill

on:
  workflow_dispatch:       # 可手動執行
  schedule:
    - cron: "0 * * * *"    # 每小時整點自動跑

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run auto-fill
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: node scripts/auto-fill.js
